name = "website-api"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
routes = [
	{ pattern = "website-api.loveh.art", custom_domain = true }
]

[vars]
OWNER_LUNA = "799319081723232267"
OWNER_KAMI = "971357228076531762"
