name = "website-api"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
routes = [
	{ pattern = "website-api.lvna.gay", custom_domain = true }
]

[vars]
DISCORD_OWNER_ID = "799319081723232267"
